    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta http-equiv="Content-Language" content="en" />
    <meta name="description" content="Task Management utility web" />
    <meta name="keywords" content="task management, gantt, java, open source, free, schedule, task scheduling, planning, project management" />
    <meta name="author" content="Jakub Neubauer" />
    <meta name="robots" content="index,follow" />
    <link rel="stylesheet" href="style.css" type="text/css" />
